# Generated by Django 5.2.14 on 2026-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
