# Generated by Django 5.2.14 on 2026-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='films/thumbnails/'),
        ),
    ]
